### ISSUE TITLE
Doesn't work any more - throws NoClassDefFoundError error

### ISSUE THREAD

**Issue by David-Hari** [luzuojin/FolderCompact#3]
I have been using this for a while now and I can't live without it. However, when I opened up my IDE today I found that the "Project" tree no longer loads any files under each project and the IDE reports the following error:

```
java.lang.NoClassDefFoundError: com/intellij/history/core/Paths
	at dev.xframe.fc.CompactedFolderNode.updateImpl(CompactedFolderNode.java:18)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.lambda$doUpdate$1(AbstractPsiBasedNode.java:214)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction$lambda$2(AnyThreadWriteThreadingSupport.kt:217)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:228)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:217)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:847)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.doUpdate(AbstractPsiBasedNode.java:167)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.lambda$update$0(AbstractPsiBasedNode.java:163)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:171)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:129)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:118)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:108)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.update(AbstractPsiBasedNode.java:163)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:88)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:32)
	at com.intellij.ui.tree.StructureTreeModel$Node.update(StructureTreeModel.java:540)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:521)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:514)
	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:432)
	at com.intellij.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:332)
	at com.intellij.ui.tree.StructureTreeModel.getNode(StructureTreeModel.java:326)
	at com.intellij.ui.tree.StructureTreeModel.getChildren(StructureTreeModel.java:348)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.computeNode(AsyncTreeModel.java:664)
	at com.intellij.ui.tree.AsyncTreeModel$Command.computeNode(AsyncTreeModel.java:537)
	at com.intellij.util.concurrency.Invoker$Task.run(Invoker.java:370)
	at com.intellij.util.concurrency.CoroutineInvokerDelegate.run(CoroutineInvokerDelegate.kt:38)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:194)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:177)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:480)
	at com.intellij.util.concurrency.CoroutineInvokerDelegate$offer$job$1.invoke(CoroutineInvokerDelegate.kt:27)
	at com.intellij.util.concurrency.CoroutineInvokerDelegate$offer$job$1.invoke(CoroutineInvokerDelegate.kt:25)
	at com.intellij.util.concurrency.SequentialBgtCoroutineInvokerDelegate$doLaunch$1$1$1.invoke(CoroutineInvokerDelegate.kt:97)
	at com.intellij.util.concurrency.SequentialBgtCoroutineInvokerDelegate$doLaunch$1$1$1.invoke(CoroutineInvokerDelegate.kt:96)
	at com.intellij.util.concurrency.BgtCoroutineInvokerDelegate$withProperContext$2.invoke(CoroutineInvokerDelegate.kt:73)
	at com.intellij.util.concurrency.BgtCoroutineInvokerDelegate$withProperContext$2.invoke(CoroutineInvokerDelegate.kt:72)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:104)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:15)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:93)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$2$lambda$1$lambda$0(cancellableReadAction.kt:31)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$2$lambda$1(cancellableReadAction.kt:29)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:155)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:27)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:93)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:77)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:64)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:15)
	at com.intellij.openapi.application.rw.InternalReadAction$readLoop$1.invokeSuspend(InternalReadAction.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
Caused by: java.lang.ClassNotFoundException: com.intellij.history.core.Paths PluginClassLoader(plugin=PluginDescriptor(name=FolderCompact, id=dev.xframe.foldercompact, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2024.2\plugins\FolderCompact-1.0.4.jar, version=1.0.4, package=null, isBundled=false), packagePrefix=null, state=active, parents=PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.performancePlugin, descriptorPath=intellij.java.performancePlugin.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 2024\plugins\java, version=242.23726.103, package=com.intellij.java.performancePlugin, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.compiler.charts, descriptorPath=intellij.java.compiler.charts.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 2024\plugins\java, version=242.23726.103, package=com.intellij.java.compiler.charts, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.impl, descriptorPath=intellij.platform.vcs.impl.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 2024\lib, version=242.23726.103, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.log.impl, descriptorPath=intellij.platform.vcs.log.impl.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 2024\lib, version=242.23726.103, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.dvcs.impl, descriptorPath=intellij.platform.vcs.dvcs.impl.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 2024\lib, version=242.23726.103, package=null, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.vcs, descriptorPath=intellij.java.vcs.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 2024\plugins\java, version=242.23726.103, package=null, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.unscramble, descriptorPath=intellij.java.unscramble.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 2024\plugins\java, version=242.23726.103, package=null, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.structuralSearch, descriptorPath=intellij.java.structuralSearch.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 2024\plugins\java, version=242.23726.103, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.collaborationTools, descriptorPath=intellij.platform.collaborationTools.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 2024\lib, version=242.23726.103, package=null, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.featuresTrainer, descriptorPath=intellij.java.featuresTrainer.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 2024\plugins\java, version=242.23726.103, package=null, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, descriptorPath=plugin.xml, path=C:\Program Files\JetBrains\IntelliJ IDEA 2024\plugins\java, version=242.23726.103, package=null, isBundled=true), )
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:157)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 57 more
```

I'm using IntelliJ IDEA 2024.2.4 (Ultimate Edition), Build #IU-242.23726.103.
I don't remember it being broken after upgrading to that version of IDEA, so it's either been broken by a minor update or it's something else entirely. I did a full Repair IDE, Invalidate Caches, etc before figuring out it was this plugin that was causing the folder tree to not show.

**Comment by luzuojin** [comment]
IDEA 2024.2.4  removed file com/intellij/history/core/Paths.   Version 1.0.5 has fixed this issue.
